# Generated by Django 4.2.3 on 2023-08-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_staff_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff_notification",
            name="statuss",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
