# Generated by Django 4.2.3 on 2023-08-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_student_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff_feeback",
            name="status",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student_feedback",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
